{{- $appProxyContext := deepCopy . }}
{{- $_ := set $appProxyContext "Values" (deepCopy (get .Values "app-proxy")) }}
{{- $_ := set $appProxyContext.Values "global" (get .Values "global") }}
{{- if (index  (get $appProxyContext "Values") "image-enrichment" "enabled") }}
{{- include "cap-app-proxy.image-enrichment.resources.role" $appProxyContext }}
---
{{- include "cap-app-proxy.image-enrichment.resources.role-binding" $appProxyContext }}
{{- end }}
