{{- define "event-reporters.rollout-reporter.rbac"}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rollout-reporter-sa
  labels: 
    app.kubernetes.io/part-of: rollout-reporter
    codefresh.io/internal: "true"
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollout-reporter-sa
  labels:
    app.kubernetes.io/part-of: rollout-reporter
    codefresh.io/internal: "true"
roleRef:
  apiGroup: ""
  kind: Role
  name: rollout-reporter-sa
subjects:
  - kind: ServiceAccount
    name: {{ include "event-reporters.rollout-reporter.serviceAccountName" . }}
{{- end }}
