{{- define "runtime-event-reporter.resources.configmap.defaults"}}
argocd.server: {{ include "codefresh-gitops-runtime.argocd.server.no-protocol-url" . }}
repo.server: {{ include "codefresh-gitops-runtime.argocd.reposerver.url" . }}
  {{- $redisServer := (include "codefresh-gitops-runtime.argocd.redis.url" .) }}
  {{- if $redisServer }}
redis.server: {{ $redisServer }}
  {{- end }}
argo-gateway.server: http://argo-gateway
resource.threadiness: '10'
app.queue.size: '1000'
max.app.retries: '5'
threadiness: '100'
{{- end }}

{{- $defaultConfig := (include "runtime-event-reporter.resources.configmap.defaults" . | fromYaml ) }}
{{- $globalOverrides := index .Values "global" "event-reporters" "config" | default dict }}
{{- $reporterOverrides := index .Values "event-reporters" "runtime-event-reporter" "config" | default dict }}
{{- $mergedConfig := mergeOverwrite $defaultConfig $globalOverrides $reporterOverrides }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: runtime-event-reporter-cmd-params-cm
  labels:
    {{- include "runtime-event-reporter.labels" . | nindent 4 }}
data:
  {{- $mergedConfig | toYaml | nindent 2 }}
