{{/* Check if installation token is string or secretKeyRef and add the value with currect structure to app-proxy values */}}
{{ $appProxyContext := deepCopy . }}
{{ $_ := set $appProxyContext "Values" (get .Values "app-proxy") }}
{{ $_ := set $appProxyContext.Values "global" (get .Values "global") }}
{{- if not $appProxyContext.Values.config.argoCdUrl }}
  {{ $argoCdUrl := include "codefresh-gitops-runtime.argocd.server.url" . }}
  {{ $_ := set $appProxyContext.Values.config "argoCdUrl" $argoCdUrl }}
{{- end }}
{{- if index (get .Values "argo-workflows") "enabled" }}
  {{- if not $appProxyContext.Values.config.argoWorkflowsUrl }}
    {{- $argoWorkflowsUrl := include "codefresh-gitops-runtime.argo-workflows.server.url" . }}
    {{- $_ := set $appProxyContext.Values.config "argoWorkflowsUrl" $argoWorkflowsUrl }}
  {{- end }}
{{- end}}
{{- include "cap-app-proxy.resources.configmap" $appProxyContext }}