
{{- if index (get .Values "argo-workflows") "enabled" }}
{{- $appProxyContext := deepCopy . }}
{{- $_ := set $appProxyContext "Values" (deepCopy (get .Values "app-proxy")) }}
{{- $_ := set $appProxyContext.Values "global" (deepCopy (get .Values "global")) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cap-app-proxy-argo-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "codefresh-gitops-runtime.argo-workflows.server.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cap-app-proxy.serviceAccountName" $appProxyContext }}
    namespace: {{ .Release.Namespace }}
{{- end }}
