apiVersion: v1
kind: Secret
metadata:
  name: codefresh-workflow-pipelines-tls
  labels:
    {{- include "codefresh-gitops-runtime.labels" . | nindent 4 }}
  {{- with .Values.global.codefresh.tls.workflowPipelinesGitWebhooks.annotations }}
  annotations: {{ . | toYaml | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- $argocdTlsCerts := index .Values "argo-cd" "configs" "tls" "certificates"}}
  {{- mergeOverwrite $argocdTlsCerts .Values.global.codefresh.tls.workflowPipelinesGitWebhooks.certificates | toYaml | nindent 2 }}
