
{{- if index (get .Values "argo-rollouts") "enabled" }}
{{- $eventReporterContext := deepCopy . }}
{{- $_ := set $eventReporterContext "Values" (get .Values "event-reporters") }}
{{- $_ := set $eventReporterContext.Values "global" (get .Values "global") }}
{{- include "event-reporters.rollout-reporter.resources" $eventReporterContext }}
---
{{/* Mapping of argo rollouts clusterrole if such is created (see https://github.com/codefresh-io/argo-helm/blob/argo-rollouts/charts/argo-rollouts/templates/controller/clusterrolebinding.yaml)
 to the reporters ServiceAccount
*/}}
  {{- if and (index (get .Values "argo-rollouts") "clusterInstall") (index (get .Values "argo-rollouts") "controller" "createClusterRole") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: codefresh-rollouts-reporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "codefresh-gitops-runtime.argo-rollouts.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "event-reporters.rollout-reporter.serviceAccountName" $eventReporterContext }}
    namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}

