{{- define "cap-app-proxy.image-enrichment.resources.role" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cap-app-proxy.fullname" . }}-enrichment
  labels:
    {{- include "cap-app-proxy.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
{{- end }}