{{- $context := deepCopy . }}
{{- $_ := set $context "Values" (deepCopy (get (index .Values "global") "event-reporters")) }}
{{- $_ := set $context.Values "global" (deepCopy (get .Values "global")) }}
{{- $valuesOverrides := index .Values "event-reporters" "cluster-event-reporter" }}
{{- $_ := mergeOverwrite $context.Values $valuesOverrides | set $context "Values" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-event-reporter.serviceAccountName" $context }}
  labels:
    {{- include "cluster-event-reporter.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ $context.Values.global.runtime.singleNamespace | ternary "Role" "ClusterRole" }}
metadata:
  name: {{ include "cluster-event-reporter.fullname" . }}
  labels:
    {{- include "cluster-event-reporter.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
  - nonResourceURLs:
    - '*'
    verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ $context.Values.global.runtime.singleNamespace | ternary "RoleBinding" "ClusterRoleBinding" }}
metadata:
  name: {{ include "cluster-event-reporter.fullname" . }}
  labels:
    {{- include "cluster-event-reporter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ $context.Values.global.runtime.singleNamespace | ternary "Role" "ClusterRole" }}
  name: {{ include "cluster-event-reporter.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cluster-event-reporter.serviceAccountName" $context }}
    namespace: {{ .Release.Namespace }}
