apiVersion: v1
kind: ConfigMap
metadata:
  name: codefresh-cm
  labels:
    {{- include "codefresh-gitops-runtime.labels" . | nindent 4 }}
data:
  base-url: {{ .Values.global.codefresh.url }}
  bootstrapRevision: {{ .Chart.AppVersion }}
  helmReleaseName: {{ .Release.Name }}
  cluster: {{ .Values.global.runtime.cluster }}
  components: |-
    {{- include "codefresh-gitops-runtime.component-list" . | nindent 4}}
  ingressClassName: {{ .Values.global.runtime.ingress.className | default "" | quote }}
  ingressController: {{ .Values.global.runtime.ingress.className | default "" | quote }}
  ingressHost: {{ include "codefresh-gitops-runtime.ingress-url" . }}
  isConfigurationRuntime: {{ .Values.global.runtime.isConfigurationRuntime | quote }} 
  singleNamespace: {{ (get .Values "app-proxy").singleNamespace | quote }}
  version: {{ .Chart.AppVersion }}